version: '2'

services:
  minio1:
    image: minio/minio:latest
    volumes:
     - ./minio_data:/data
    ports:
     - "9000:9000"
    environment:
     MINIO_ACCESS_KEY: username
     MINIO_SECRET_KEY: private_pass
    command: server /data
